### ISSUE TITLE
Define and make basic app logic

### ISSUE THREAD

**Issue by RomchiLolchi** [RomchiLolchi/SuperSchoolboyRemastered#15]
### TODO
- [x] Basic training logic
- [x] Basic statistics
- [x] Ads (with showing control panel in Firebase; #12)
- [x] Russian translation (#14)
- [x] Text formatting in text windows
