### ISSUE TITLE
Make the basic design of the app

### ISSUE THREAD

**Issue by RomchiLolchi** [RomchiLolchi/SuperSchoolboyRemastered#7]
Need to implement the full MVP design in the application itself

### TODO:
- [x] Make basic design from Figma
- [x] Write basic logic of transition between screens
- [x] #9

### Screens' design to implement:
- [x] Login Screen
- [x] MainActivity Screen
- [x] TrainingActivity Screen
- [x] SettingsActivity Screen
- [x] ~Statistics screen~ (Useless until the basic logic is done, may not be included in the MVP)
- [x] Text for parents and teachers screen
- [x] Text for kids screen
- [x] About app screen
